config/routes.rb
BreakableToy2::Application.routes.draw do
  devise_for :users, :skip => [:password]

  resources :users, only: [:show] do
    resources :lists, only: [:index]
  end

  resources :lists do
    resources :list_items, only: [:create]
  end

  resources :list_items, only: [:show, :edit, :destroy, :update] do
    resources :comments, only: [:create]
  end

  resources :comments, only: [:destroy]

  root :to => 'welcome#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body

  validates_presence_of :body

  belongs_to :list_item
  belongs_to :user
end

app/models/list.rb
class List < ActiveRecord::Base
  attr_accessible :title, :state_event, :description

  state_machine :state, :initial => :drafted do

    event :publish do
      transition :drafted => :published
    end

    event :unpublish do
      transition :published => :drafted
    end

    state :drafted
    state :published
  end

  validates_presence_of :user, :title
  validate :cannot_be_over_7, on: :create

  belongs_to :user, :inverse_of => :lists
  has_many :list_items, :inverse_of => :list, dependent: :destroy

  def cannot_be_over_7
    unless user.nil? or user.lists.count < 7
      errors.add(:title, "You can only have seven lists.")
    end
  end

  def self.viewable_by(user)
    if user.nil?
      where("state = ?", 'published')
    else
      where("state = ? OR user_id = ?", 'published', user.id)
    end
  end
end

app/models/list_item.rb
class ListItem < ActiveRecord::Base
  attr_accessible :title, :description

  validates_presence_of :title, :list
  validate :cannot_be_over_7, on: :create

  belongs_to :list, :inverse_of => :list_items
  has_many :comments

  def cannot_be_over_7
    unless list.nil? or list.list_items.count < 7
      errors.add(:title, "You can only have seven items.")
    end
  end

  def wiki_url
    "http://www.en.wikipedia.org/wiki/#{wiki_safe_title}"
  end

  private
  def wiki_safe_title
    # This gets rid of all unsafe link characters
    edited_title = title.tr("^A-Za-z0-9 ", '')
    # Then combines the words with an underscore
    final_title = edited_title.split.map{|s| s.capitalize}.join("_")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :authentication_keys => [:login]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :username, :email, :password, :password_confirmation, :remember_me, :login
  # attr_accessible :title, :body

  attr_accessor :login

  validates_presence_of :username
  validates_uniqueness_of :username

  extend FriendlyId
  friendly_id :username

  has_many :lists, :inverse_of => :user, dependent: :destroy
  has_many :list_items, through: :lists
  has_many :comments, :inverse_of => :user, dependent: :destroy

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def after_sign_out_path_for(resource)
    root_path
  end

  def after_sign_in_path_for(resource)
    user_lists_path(current_user)
  end

  def after_inactive_sign_up_path_for(resource)
    root_path
  end
end

app/controllers/comments_controller.rb
class CommentsController < ActionController::Base
  def create
    @item = ListItem.find(params[:list_item_id])
    @comment = @item.comments.new(params[:comment])
    @comment.user = current_user

    if @comment.save
      redirect_to list_item_path(@item), notice: "Successfully added comment"
    else
      redirect_to list_item_path(@item), alert: "Did not create comment"
    end
  end

  def destroy
    @comment = Comment.find(params[:id])
    @item = @comment.list_item

    @comment.destroy
    redirect_to list_item_path(@item), notice: "Comment successfully deleted."
  end
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  def show
    @item = ListItem.find(params[:id])
    @comments = @item.comments
    @comment = @item.comments.new
  end

  def create
    @list = List.find(params[:list_id])
    @item = ListItem.new(params[:list_item])
    @item.list = @list

    if @item.save
      redirect_to list_path(@list), notice: 'Successfully created new item.'
    else
      redirect_to list_path(@list), alert: "Failed to create item."
    end
  end

  def edit
    @item = current_user.list_items.find(params[:id])
    @list = @item.list
  end

  def update
    @item = current_user.list_items.find(params[:id])
    if @item.update_attributes(params[:list_item])
      redirect_to list_item_path(@item), notice: "Item updated successfully."
    else
      redirect_to list_path(@item.list_id), alert: "Failed to edit item."
    end
  end

  def destroy
    @item = current_user.list_items.find(params[:id])
    @list = @item.list
    @item.destroy

    redirect_to list_path(@list), notice: "Item deleted successfully."
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]

  def index
    if params[:user_id]
      @user = User.find(params[:user_id])
      @lists = @user.lists.order("created_at ASC").viewable_by(current_user)
    else
      @search = List.order('created_at DESC').viewable_by(nil).search(params[:q])
      @lists = @search.result.page(params[:page]).per(7)
    end
  end

  def new
    @list = current_user.lists.new
  end

  def create
    @list = current_user.lists.new(params[:list])

    if @list.save
      flash[:notice] = "List created successfully."
      redirect_to user_lists_path(current_user)
    else
      flash[:alert] = "Failed to create list."
      render action: "new"
    end
  end

  def edit
    @list = current_user.lists.find(params[:id])
  end

  def update
    @list = current_user.lists.find(params[:id])

    if @list.update_attributes(params[:list])
      redirect_to user_lists_path(current_user), notice: "List successfully changed."
    else
      redirect_to user_lists_path(current_user), alert: "Failed to change list title."
    end
  end

  def show
    @list = List.viewable_by(current_user).find(params[:id])
    if current_user == @list.user
      @item = current_user.list_items.new
    end
  end

  def destroy
    @list = current_user.lists.find(params[:id])

    @list.destroy
    redirect_to user_lists_path(current_user), notice: "List successfully deleted."
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  respond_to :html

  def index
    # occasionally the redirect to root path returns
    # a status code of 304 (Not Modified) which causes
    # the page to display a not signed in page when
    # actually signed in or vice-versa. This is an
    # attempt to addres that issue.
    # More info @
    # http://archives.ryandaigle.com/articles/2009/8/6/what-s-new-in-edge-rails-cleaner-restful-controllers-w-respond_with/
    if current_user
      respond_with current_user
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Faven</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= csrf_meta_tags %>
    <link href='http://fonts.googleapis.com/css?family=Orienta' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Kite+One' rel='stylesheet' type='text/css'>
  </head>
  <body>

    <div id="canvas_div">
      <canvas></canvas>
      <div id="buttons">
        <input type="button" id="clear" value="Clear">
      </div>
      <p class="writing">You can draw something!</p>
    </div>

    <div id="airplane">
      <%= image_tag "plane.png" %>
    </div>

    <%= render :partial => 'shared/header' %>

    <%= yield %>

    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>
    <%= javascript_include_tag "application" %>

  </body>
</html>

app/views/list_items/edit.html.erb
<div class="body_container">
  <h1 class="writing">Edit item</h1>

  <%= simple_form_for @item do |f| %>
    <%= f.input :title %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/list_items/show.html.erb
<div class="body_container">
  <h1 class="writing"><%= @item.title %></h1>

  <%- if @item.description %>
    <div class="description_container">
      <p>Description &amp Extra Info:</p>
      <p><%= auto_link(@item.description) %></p>
    </div>
  <%- end %>

  <div class="comments">
    <p class="writing">Comments</p>
    <%# I have to pop the last one out because %>
    <%# the controller was making a new comment entry %>
    <%# that was interfering with the blank? method %>
    <%- @comments.pop %>
    <%- unless @comments.blank? %>
      <%- @comments.each do |comment| %>
        <%= comment.user.username + ": " %>
        <%= comment.body %>

        <%- if current_user == comment.user %>
          <%= link_to "Delete", comment_path(comment), method: :delete, data: { confirm: "Delete comment?" } %>
        <%- end %>
        <br/>
      <%- end %>
    <%- end %>
  </div>

  <%- unless current_user.nil? %>
    <%= simple_form_for [@item, @comment] do |f| %>
      <%= f.input :body, label: "Comment" %>
      <%= f.button :submit %>
    <%- end %>
  <%- end %>

  <%- if current_user == @item.list.user %>
    <div class="spacing_for_list">
      <p>Note: Other users do not see anything below this.</p>
    </div>

    <%= simple_form_for @item do |f| %>
      <%= f.input :description %>
      <%= f.button :submit, "Change info" %>
    <%- end %>
  <%- end %>
</div>

app/views/lists/_description_field.html.erb
<%= simple_form_for @list do |f| %>
  <%= f.input :description %>
  <%= f.button :submit, "Change description" %>
<%- end %>

app/views/lists/_form_new.html.erb
<div class="body_container">
  <%= simple_form_for @list do |f| %>
    <%= f.input :title, wrapper_html: { class: "no_scale" }, :autofocus => true %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/lists/_list_item_creation.html.erb
<%= simple_form_for [@list, @item] do |f| %>
  <%= f.input :title, label: "Add an item", :autofocus => true %>
  <%= f.button :submit %>
<% end %>

app/views/lists/_publish_button.html.erb
<%= simple_form_for @list do |f| %>
  <%- unless @list.published? %>
    <div class="publish_button">
      <%= f.hidden_field :state_event, value: "publish" %>
      <%= f.button :submit, "Publish" %>
    </div>
  <%- else %>
    <div class="unpublish_button">
      <%= f.hidden_field :state_event, value: "unpublish" %>
      <%= f.button :submit, "Unpublish" %>
    </div>
  <%- end %>
<%- end %>

app/views/lists/edit.html.erb
<div class="body_container">
  <h1 class="writing">Edit list</h1>

  <%= render 'form_new' %>
</div>

app/views/lists/index.html.erb
<div class="body_container">
  <h1 class="writing">List title</h1>

  <%- unless params[:user_id] %>
    <%= search_form_for @search do |f| %>
      <div class="field">
        <%= f.label :title_cont, "Title contains" %>
        <%= f.text_field :title_cont %>
      </div>
      <div class="actions"><%= f.submit "Search" %></div>
    <%- end %>
    <%= paginate @lists %>
  <%- end %>

  <ol>
    <%- @lists.each do |list| %>
      <div class="list_container">
        <div class="list_title"><li><%= link_to list.title, list_path(list) %></li></div>
        <div class="button to_list"><%= link_to "To List", list_path(list) %></div>
        <%- unless current_user.nil? %>
          <%- if current_user == @user %>
            <div class="button edit_button"><%= link_to "Edit list", edit_list_path(list) %></div>
            <div class="button delete_button"><%= link_to 'Delete list', list_path(list), method: :delete, data: { confirm: "Delete \"#{list.title}\"?" } %></div>
          <%- end %>
        <%- end %>
      </div>
    <%- end %>
  </ol>

  <%- unless current_user.nil? %>
    <%- if current_user == @user %>
      <%- if @user.lists.count < 7 %>
        <div class="button add_list_button">
          <%= link_to "Add a list", new_list_path %>
        </div>
      <%- end %>

      <p>To share this link, give this URL...</p>
      <%= "http://faven.herokuapp.com/users/#{@user.username}/lists" %>
    <%- end %>
  <%- end %>
</div>

app/views/lists/new.html.erb
<div class="body_container">
  <h1 class="writing">Add a list</h1>

  <%= render 'form_new' %>

  <div class="button add_list_cancel"><%= link_to "Cancel", user_lists_path(current_user) %></div>
</div>

app/views/lists/show.html.erb
<div class="body_container">
  <h1 class="writing"><%= @list.title %></h1>
  <%- if @list.description %>
    <div class="description_container">
      <p>Description:</p>
      <p><%= auto_link(@list.description) %></p>
    </div>
  <%- end %>

  <ol>
    <%- @list.list_items.each do |item| %>
      <div class="list_container">
        <div class="item_title"><li><%= link_to item.title, list_item_path(item) %></li></div>
        <div class="button wiki"><%= link_to "Wiki", item.wiki_url, target: "_blank" %></div>
        <%- if current_user == @list.user %>
          <div class="button edit_button"><%= link_to "Edit item", edit_list_item_path(item) %></div>
          <div class="button delete_button"><%= link_to 'Delete item', list_item_path(item), method: :delete, confirm: "Delete \"#{item.title}\"?" %></div>
        <%- end %>
      </div>
    <%- end %>
  </ol>

  <%- if current_user == @list.user %>
    <div class="spacing_for_list">
      <p>Note: Other users do not see anything below this.</p>
      <p>Must click publish button for other users to view this list</p>
    </div>
  <%- end %>

  <%- if @list.list_items.count < 7 %>
    <%- if current_user == @list.user %>
      <%= render 'list_item_creation' %>
    <%- end %>
  <%- end %>

  <%- if current_user == @list.user %>
    <div class="spacing_for_list">
      <div class="description_div">
        <%= render 'description_field' %>
      </div>
    </div>
  <%- end %>

  <%- if current_user == @list.user %>
    <%= render 'publish_button' %>
  <%- end %>
</div>

app/views/shared/_header.html.erb
<div class="header_container">
  <div class="header_wrapper">
    <div class="logo_div">
      <a href='/'><%= image_tag "faven_logo.png" %></a>
    </div>

    <div class="nav_div">
      <nav class="sign_in_out_container">
        <ul>
          <li class="public_lists_link"><%= link_to "Public Lists", lists_path %></li>
          <% if user_signed_in? %>
            <li class="button"><%= link_to "My lists", user_lists_path(current_user) %></li>
            <li class="button sign_out_link"><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
          <%- else %>
            <li class="button"><%= link_to "Register", new_user_registration_path %></li>
            <li class="button"><%= link_to "Login", user_session_path %></li>
          <%- end %>
        </ul>
      </nav>
    </div>
  </div>
</div>

<div class="notice_container">
  <%- if notice %>
    <p class="notice"><%= notice %></p>
  <%- end %>
  <%- if alert %>
    <p class="alert"><%= alert %></p>
  <%- end %>
</div>

app/views/welcome/index.html.erb
<div class="body_container">
  <h1 class="title faven">Faven</h1>
  <div class="writing intro">
    <p>Welcome to Faven!</p>
    <p>Faven is from the words favorite &amp seven.</p>
    <p>Faven keeps track of a list of your favorite things.</p>
    <p>The unique part is that you are only allowed to have seven lists of seven items.</p>
    <p>Why only seven you may be asking?</p>
    <p>There are seven days in the week, seven colors in the rainbow, and seven wonders of the world.</p>
    <p>In order to continue that tradition, I limited each list to contain only seven items.</p>
  </div>

  <div class="link_to_lists_container">
    <%- if user_signed_in? %>
      <div class="list_link_wrapper">
        <a class="list_link"><%= link_to "Go to Lists", user_lists_path(current_user) %></a>
      </div>
    <%- end %>
  </div>
</div>